/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package UCNDiscordBot;

import javax.security.auth.login.LoginException;

import UCNDiscordBot.APIS.GetAPIKey;
import UCNDiscordBot.Listeners.MessageListener;
import UCNDiscordBot.Listeners.ReactionListener.AddReact;
import UCNDiscordBot.Listeners.ReactionListener.ReactRole;
import UCNDiscordBot.MusicPlayer.*;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.entities.Activity;
import net.dv8tion.jda.api.hooks.ListenerAdapter;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.ChunkingFilter;
import net.dv8tion.jda.api.utils.MemberCachePolicy;

public class App extends ListenerAdapter {
    private static String discordToken = new GetAPIKey().getDiscordKey();

    public static void main(String[] args) throws LoginException {
        JDABuilder builder = JDABuilder.createDefault(discordToken);

        // Set the activity for the session
        builder.setActivity(Activity.playing("with your sister"));

        // Set event listeners
        builder.addEventListeners(new MessageListener());
        builder.addEventListeners(new MusicPlayer());
        builder.addEventListeners(new AddReact());
        builder.addEventListeners(new ReactRole());

        // Set enabled intents
        builder.setEnabledIntents(GatewayIntent.GUILD_MEMBERS, GatewayIntent.GUILD_MESSAGES,
                GatewayIntent.MESSAGE_CONTENT, GatewayIntent.GUILD_VOICE_STATES,
                GatewayIntent.GUILD_EMOJIS_AND_STICKERS);

        // Set member cache and chunking
        builder.setMemberCachePolicy(MemberCachePolicy.ALL);
        builder.setChunkingFilter(ChunkingFilter.ALL);

        // Build that bitch
        builder.build();
    }
}